module.exports = {
   age: new Date(2004, 5, 18),
   start: new Date(2021, 8, 1),
   location: 'Kielce(Poland)',
   social: [
      {
         title: 'tel',
         icon: '/icons/telegram.svg',
         link: 'https://t.me/nightwanderer2004',
      },
      {
         title: 'git',
         icon: '/icons/github.svg',
         link: 'https://github.com/NightWanderer2004',
      },
   ],
   skills: [
      { title: 'Prog. langs', list: ['JS / TS', 'C / C++', 'Python'] },
      { title: 'Frontend', list: ['React+Redux', 'NextJS', 'TailwindCSS', '11ty'] },
      { title: 'Backend', list: ['NestJS / Express', 'MongoDB / PostgreSQL', 'GraphQL'] },
      { title: 'Tools', list: ['VS Code', 'GitHub', 'Notion', 'GPT'] },
      { title: 'Other', list: ['Browsers', 'MacOS'] },
   ],
   projects: [
      {
         title: 'Дом ОСББ',
         url: 'https://dom-osbb.netlify.app',
         desc: 'app for checking apartment dues',
         img: '/projects/dom-osbb.png',
         info: 'Made a smooth app using framer-motion & shadcn. Also I made a connection to Google Sheets API, implemented dynamic routes for many houses, that automaticaly are connected to table',
      },
      {
         title: 'Fancy MBTI',
         url: 'https://fancy-mbti.com',
         desc: 'AI to help with well-being',
         img: '/projects/fancy-mbti.png',
         info: 'Made a super tool to help people with finding their power and weaknesses. App is using GPT-4 and show response in real time',
      },
      {
         title: 'Valerii Vasianovych',
         url: 'https://valerii-vasianovych.site',
         desc: 'portfolio page for friend generated based on local data file',
         img: '/projects/valerii-vasianovych.png',
         info: 'Made a simple portfolio page',
      },
      {
         title: 'Beauty.Laboratorie',
         url: 'https://cosmetcab.dp.ua/',
         desc: 'site for cosmetology studio',
         img: '/projects/beauty.laboratorie.png',
         info: 'Cosmetology studio page with appointment form. Used NextAuth for admin-panel',
      },
      {
         title: 'Suimiro',
         url: 'https://suimiro.netlify.app/',
         desc: 'web blog',
         img: '/projects/suimiro.png',
         info: 'Static generated blog made using 11ty and vanilla JS. My first great project!',
      },
      {
         title: 'Actify',
         url: 'https://actify-you.netlify.app',
         desc: 'app for activity',
         img: '/projects/actify.png',
         info: 'Connected to BoredAPI I made a smooth app to generate random tasks',
      },
      {
         title: 'Tokners',
         url: 'https://my-tokners.netlify.app',
         desc: 'landing page for crypto company',
         img: '/projects/tokners.png',
         info: 'Just first practice with React. Also I trained my MERN stack here',
      },
   ],
   myFavs: ['Japan', 'philosophy', 'psychology', 'anime', 'MBTI', 'design'],
   myEnv: {
      computer: 'Macbook Air M1',
      monitor: 'Xiaomi Monitor 1C 23.8"',
      keyboard: 'Anne Pro 2 (brown switches)',
      mouse: 'HP 280 Silent',
      image: '/env3.jpg',
   },
   work: [
      { title: 'Freelancer', date: 'apr 2021 - aug 2021', desc: 'making simple landing pages and fixes in HTML, CSS and logos' },
      {
         title: 'Fullstack Trainee',
         company: 'ZenBit',
         date: 'aug 2022 - oct 2022',
         desc: 'developing frontend and backend for own freelance platform',
      },
      {
         title: '#BuildInPublic',
         date: 'sep 2023 - now',
         desc: 'working as a solo developer, I create indie projects using NextJS. My focus is on sleek design with efficient functionality',
      },
   ],
}
